apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildfire-api
  labels:
    app: wildfire-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wildfire-api
  template:
    metadata:
      labels:
        app: wildfire-api
    spec:
      containers:
        - name: wildfire-api
          image: ghcr.io/plemvan/wildfireprediction:latest
          ports:
            - containerPort: 8000
          env:
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: wildfire-secrets
                  key: S3_BUCKET
            - name: MLFLOW_TRACKING_URI
              valueFrom:
                secretKeyRef:
                  name: wildfire-secrets
                  key: MLFLOW_TRACKING_URI
            - name: MLFLOW_TRACKING_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wildfire-secrets
                  key: MLFLOW_TRACKING_USERNAME
            - name: MLFLOW_TRACKING_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wildfire-secrets
                  key: MLFLOW_TRACKING_PASSWORD
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: wildfire-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: wildfire-secrets
                  key: AWS_SECRET_ACCESS_KEY
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
# wildfire api deployment