apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wildfire-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: onyxia
  rules:
    - host: wildfire-api.user.lab.sspcloud.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wildfire-api
                port:
                  number: 80